runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /\.well\-known\/acme\-challenge\/.*
  script: letsencrypt.app

- url: /
  static_files: output/index.html
  upload: output/index.html

- url: ^(?!/\.well\-known\/acme\-challenge\/)/(.*)
  static_files: output/\1
  upload: output/(.*)

skip_files:
    - ^venv/.*$
