version: 2.0
jobs:
  build:
    docker:
      - image: circleci/python:2.7.15-stretch
    steps:
      - checkout
      - run:
          name: Install locales
          command: |
              sudo locale-gen fr_FR.UTF-8
              sudo locale-gen fr fr_FR fr_FR.UTF-8
      - run:
          name: Install python-virtualenv
          command: sudo apt-get install python-virtualenv
      - run:
          name: install python dependencies
          command: |
              mkdir -p ./venv
              virtualenv ./venv
              . venv/bin/activate
              pip install pelican webassets cssmin markdown
      - run: mkdir output
      - run:
          name: make html
          command: |
              . venv/bin/activate
              make html
      - run: deactivate
      - run: pip install -t lib -r requirements.txt
  deploy:
    filters:
     branches:
       only:
          - master
    docker:
      - image: google/cloud-sdk:alpine
    steps:
      - checkout
      - run:
        name: Authenticate with Google Cloud
        command: |
          echo $CLIENT_SECRET > /home/circleci/.gcloud-key
          gcloud auth activate-service-account --key-file=/home/circleci/.gcloud-key
      - run:
        name: Deploy to Google App Engine
        commmand: |
          gcloud config set project $GCLOUD_PROJECT
          gcloud -q app deploy app.yaml --promote
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
